### PR TITLE
catch edge case where streamer logic fails on small response sizes

### PR DESCRIPTION
**Pull request by pkarman**
e.g. 320 bytes

### CODE REVIEW

**Comment by kookster** [comment]
do you have an example file where this is failing?

**Comment by pkarman** [comment]
https://pop-up-archive-staging.herokuapp.com/api/items/24463/audio_files/29738/transcript_text

was failing with `Undefined method '>' for nil:NilClass <NoMethodError>`

**Comment by kookster** [comment]
seems like calling to_i on the values in the loop would resolve this with less change, I'll try it out.

**Comment by kookster** [comment]
closing in favor of #31

**Pull request closed without merging**
