### PR TITLE
AudioMonster cut_wav and slice_wav expect integers

### PR DESCRIPTION
**Pull request by pkarman**

### CODE REVIEW

**Comment by kookster** [comment]
slice doesn't have to be an integer, I definitely use it with options like: 
```json
{"start": "00:57:39.0", "finish": "00:59:38.9"}
```

**Comment by kookster** [comment]
It does look like there is a validation in audio monster that makes some assumptions about getting an int, but `sox` handles decimals just fine, so that seems more like a bug in audio monster, not something to enforce in this way in fixer.

**Comment by kookster** [comment]
I believe this is better handled in audio monster, added ticket here.
https://github.com/PRX/audio_monster/issues/8

**Comment by pkarman** [comment]
agreed. closing.

**Pull request closed without merging**
