### PR TITLE
Fix creating sequences posted from the api controller

### LINKED ISSUE #33: example of tasks with sequence
The tests have an example of creating a job with a sequence of tasks. That works ok directly at the model level.

However, I cannot seem to POST a job via the http interface with a sequence of tasks. The relevant controller seems to be `app/controllers/api/jobs_controller.rb` in the `job_params` method.

Can you include an example of creating a job with a task sequence, either here or (preferably) as an example on the fixer_client repo.

### PR DESCRIPTION
**Pull request by kookster**
The main issue is more complex whitelisting of params
Should fix #33

### CODE REVIEW

**Comment by kookster** [comment]
@pkarman review when you can?

**Comment by pkarman** [comment]
this looks correct to me. 

would you prefer that I check out the branch and do a live test before giving my +1?

**Comment by kookster** [comment]
Our standard for approval is visual review and passing tests, but if you want to also merge and test locally first, that's fine with me too.

**Comment by pkarman** [comment]
I'll trust the usual standard and passing rspec tests. +1 to merge.

**Pull request merged**
